# Generated by Django 6.1.1 on 2026-10-02 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='accounts.profilclient', verbose_name='Profil Client'),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
