# Generated by Django 6.1.1 on 2026-10-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adresse_profil_alter_profilclient_user'),
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='state',
        ),
        migrations.AlterField(
            model_name='adresse',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_city', to='cities_light.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_country', to='cities_light.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_region', to='cities_light.region', verbose_name='Région'),
        ),
    ]
