# Generated by Django 6.0.5 on 2026-06-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image du produit'),
        ),
    ]
