# Generated by Django 6.0.5 on 2026-08-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('customer', '0002_initial'),
        ('sessions', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20, verbose_name='Type de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Mode de règlement',
                'verbose_name_plural': 'Modes de règlement',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('destination', models.CharField(verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de livraison'), ('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('livree', 'Livrée')], default='en_attente', max_length=100, verbose_name='Statut de la commande')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_user', to='customer.profil')),
                ('mode_reglement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='store.modedereglement', verbose_name='Mode de règlement')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='store.commande', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='vendor.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('expedie', 'Expédié'), ('en_transit', 'En transit'), ('livre', 'Livré'), ('echec', 'Échec de livraison')], default='en_attente', max_length=100, verbose_name='Statut de la livraison')),
                ('address', models.TextField(max_length=100, verbose_name='Adresse de livraison')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('expected_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Pays')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison_commande', to='store.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_user', to='customer.profil')),
                ('session_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='Clé de session')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.panier', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='vendor.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
