# Generated by Django 6.0.4 on 2026-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
