# Generated by Django 5.2.17 on 2026-09-02 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_panier_session_key'),
        ('vendor', '0006_rename_categorie_id_produit_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='livraison',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='modedereglement',
            name='slug',
        ),
        migrations.AddField(
            model_name='commande',
            name='profil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Profil Utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panier',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL, verbose_name='Profil Utilisateur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé de session'),
        ),
        migrations.RemoveField(
            model_name='panier',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='slug',
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.panier', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='vendor.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
