# Generated by Django 5.2.17 on 2026-09-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('store', '0004_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Département / Région'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Ville'),
        ),
    ]
