# Generated by Django 6.0.5 on 2026-08-25 21:55

import customer.models.profil
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('note', models.PositiveSmallIntegerField(verbose_name='Note du produit')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire utilisateur')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approbation')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaiementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant')),
                ('statut', models.CharField(default='en_attente', max_length=50, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('moderateur', 'Moderateur'), ('visiteur', 'Visiteur')], max_length=100, verbose_name='Rôle')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=customer.models.profil.photo_path, verbose_name='Photo')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('type', models.CharField(choices=[('domicile', 'Domicile'), ('bureau', 'Bureau'), ('autre', 'Autre')], default='domicile', max_length=20, verbose_name="Type d'adresse")),
                ('street', models.CharField(max_length=255, verbose_name='Rue')),
                ('is_default', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Ville')),
                ('country', models.ForeignKey(blank=True, default="Côte d'Ivoire", max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
