# Generated by Django 6.0.4 on 2026-06-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='savedpaymentmethod',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
    ]
