# Generated by Django 6.0.5 on 2026-08-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_produit', to='vendor.produit', verbose_name='produit'),
        ),
        migrations.AddField(
            model_name='favoris',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_produit', to='vendor.produit', verbose_name='Produit'),
        ),
    ]
