# Generated by Django 5.2.17 on 2026-09-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('vendeur', 'Vendeur'), ('moderateur', 'Moderateur'), ('visiteur', 'Visiteur')], max_length=100, verbose_name='Rôle'),
        ),
    ]
