# Generated by Django 5.2.17 on 2026-09-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('customer', '0002_alter_profil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Département / Région'),
        ),
    ]
