# Generated by Django 6.0.5 on 2026-08-25 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenpaiementmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyen_paiements', to='store.modedereglement', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='paiementmodel',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='store.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_user', to=settings.AUTH_USER_MODEL, verbose_name='Profil utilisateur'),
        ),
        migrations.AddField(
            model_name='paiementmodel',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='customer.profil', verbose_name='Profil utilisateur'),
        ),
        migrations.AddField(
            model_name='moyenpaiementmodel',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to='customer.profil', verbose_name='Profil utilisateur'),
        ),
        migrations.AddField(
            model_name='favoris',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='customer.profil', verbose_name='Profil utilisateur'),
        ),
        migrations.AddField(
            model_name='avis',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_user', to='customer.profil', verbose_name='Profil utilisateur'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress_user', to='customer.profil', verbose_name='Profil Utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together={('profil', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('profil', 'product')},
        ),
    ]
