# Generated by Django 6.0.5 on 2026-08-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Pays'),
        ),
    ]
