# Generated by Django 6.0.5 on 2026-06-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiementmodel',
            name='type_paiement',
            field=models.CharField(choices=[('mobile', 'Mobile Money'), ('visa', 'Visa'), ('wave', 'Wave'), ('paypal', 'Paypal')], default='mobile', max_length=20),
        ),
    ]
