# Generated by Django 6.0.5 on 2026-06-06 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_moyenpaiementmodel_type_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avismodel',
            name='note',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
