# Generated by Django 6.1.1 on 2026-10-05 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la Categorie')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug de la Categorie')),
                ('description', models.TextField(blank=True, verbose_name='Description de la Categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la Boutique')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug de la Boutique')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de la Boutique')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='Contact de la Boutique')),
                ('quartier', models.CharField(max_length=255, verbose_name='Quartier de la Boutique')),
                ('secteur_activite', models.CharField(blank=True, choices=[('Électronique', 'Électronique'), ('Mode', 'Mode'), ('Alimentaire', 'Alimentaire'), ('Santé et Beauté', 'Santé et Beauté'), ('Sport et Loisirs', 'Sport et Loisirs'), ('Autres', 'Autres')], max_length=255, verbose_name="Secteur d'activité de la Boutique")),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Pays de la Boutique')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Région de la Boutique')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='Ville de la Boutique')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du Produit')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug du Produit')),
                ('description', models.TextField(blank=True, verbose_name='Description du Produit')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix du Produit')),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.PositiveIntegerField(verbose_name='Quantité en Stock du Produit')),
                ('boutique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogues.boutique', verbose_name='Boutique du Produit')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.categorie', verbose_name='Catégorie du Produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('image', models.ImageField(upload_to='produits/', verbose_name='Image')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogues.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image Produit',
                'verbose_name_plural': 'Images Produits',
            },
        ),
    ]
