# Generated by Django 6.0.4 on 2026-06-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
    ]
