# Generated by Django 6.1.1 on 2026-10-06 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_adresse_state_alter_adresse_city_and_more'),
        ('catalogues', '0002_boutique_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('type', models.CharField(choices=[('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20, verbose_name='Type de paiement')),
            ],
            options={
                'verbose_name': 'Mode de règlement',
                'verbose_name_plural': 'Modes de règlement',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('commande_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='DetailsCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commandes.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catalogues.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Détail Commande',
                'verbose_name_plural': 'Détails Commandes',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(related_name='commandes', through='commandes.DetailsCommande', to='catalogues.produit', verbose_name='Produits'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='DetailsPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_panier', to='catalogues.produit', verbose_name='Produit')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commandes.panier', verbose_name='Panier')),
            ],
            options={
                'verbose_name': 'Détail Panier',
                'verbose_name_plural': 'Détails Paniers',
            },
        ),
    ]
